package com;

public class Utiles {
                                                                                                                                                                                                                                                                                                                                              public static void mostrarTabla(int [] tabla) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.print( "[ ");                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              for(int elemento : tabla) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  System.out.print(elemento +"\t");                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              System.out.print( "]");          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }
}
